# Generated by Django 5.2.6 on 2025-09-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approach',
        ),
        migrations.AddField(
            model_name='post',
            name='counted_comments',
            field=models.IntegerField(default=0),
        ),
    ]
